#!/usr/bin/env python3
"""Qualify libPorpoise constructors against a personal Wind Waker module.

The supplied private raw translation is certified before its three leaf bodies
are extracted into ignored build files. A matched baseline uses today's emitted
CPU helpers, inline FP/gather memory, and prepaid blocks at the same compiler
flags as the guarded native helper. No guest bodies enter the tracked tests.

The benchmark measures constructor calls, including a host-readiness callback;
it neither measures routed module dispatch nor predicts game frame rates.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import statistics
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
LEAVES = (
    (0x8030D09C, 0x8030D0C8, "d7a76bde12b0c49ed8de5950d66f39bd61c8512dd33392bff7cdd8611fdcb396"),
    (0x8030D618, 0x8030D64C, "a0f3e37bfab1629224a2a4e64c5d6f4b320f725fa56b98eb6afc82cb0e8d03b2"),
    (0x8030D698, 0x8030D6C0, "947ed8f260c31aa05ad4707c1f383c21e6d408e984c07f4ebd6d94cb3ca06c65"),
)


def sha(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for data in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(data)
    return digest.hexdigest()


def load(name: str, relative: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / relative)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def current_header(private_header: Path) -> str:
    """Read literal emitted helper lines without running the game generator."""
    tree = ast.parse((ROOT / "scripts/generate_composite.py").read_text(encoding="utf-8"))
    main = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "main")
    lines = []
    started = False
    for node in main.body:
        if (isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and
                isinstance(node.value.func, ast.Attribute) and
                isinstance(node.value.func.value, ast.Name) and
                node.value.func.value.id == "lines" and node.value.func.attr == "append" and
                len(node.value.args) == 1 and isinstance(node.value.args[0], ast.Constant) and
                isinstance(node.value.args[0].value, str)):
            value = node.value.args[0].value
            if value == "// Generated by generate_composite.py -- do not edit.":
                started = True
            if started:
                lines.append(value)
        elif started:
            break
    if not lines or not any("ppc_psq_store_inline" in line for line in lines):
        raise ValueError("current generated helper prefix is unsupported")
    private = private_header.read_text(encoding="utf-8")
    start = private.index("static inline u32 dolrecomp_rotl32")
    end = private.index("// Function entry points", start)
    lines += [private[start:end], "#endif /* RECOMP_COMPOSITE_H */", ""]
    return "\n".join(lines)


def make_baselines(args, output: Path):
    text = args.translation.read_text(encoding="utf-8")
    fast = load("porpoise_fast_blocks", "scripts/windows/fast_blocks.py")
    headers = load("porpoise_chunk_headers", "scripts/windows/chunk_headers.py")
    functions = []
    for index, (start, end, expected) in enumerate(LEAVES):
        begin = text.index(f"\nlabel_{start:08X}:")
        finish = text.index(f"\nlabel_{end:08X}:", begin)
        body = text[begin:finish]
        actual = hashlib.sha256(" ".join(body.split()).encode()).hexdigest()
        if actual != expected:
            raise ValueError(f"private translated constructor {start:08X} is not certified: {actual}")
        leaf = (f"void porpoise_raw_{index}(CPUState* ctx) {{\n"
                "    bool cycle_block_prepaid = false;\n" + body +
                "\nreturn_dispatch_803096E0:\n    return;\n}\n")
        functions.append(leaf)
        # Compile a baseline without the optional native constructor routing.
        # Its generic prepaid transform may therefore optimize these leaves.
        prepared, count = fast.transform_function(leaf.rstrip().split("\n"), [])
        if count != 1:
            raise ValueError(f"expected one prepaid constructor block: {start:08X}, got {count}")
        functions.append("\n".join(prepared).replace(f"porpoise_raw_{index}", f"porpoise_prepared_{index}") + "\n")
    header = output / "generated.h"
    header.write_text(current_header(args.header), encoding="utf-8")
    directory = output / "chunks"
    directory.mkdir(parents=True, exist_ok=True)
    source = directory / "matched_constructors.c"
    content = fast.INCLUDE + "\n".join(functions)
    content = headers.transform(content, source, inline_fp=True, gather_pipe=True)
    source.write_text(content, encoding="utf-8")
    return source, header


def run(args):
    if os.name != "nt":
        raise ValueError("this oracle harness loads a Windows personal module")
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    for path in (args.module, args.translation, args.header):
        if not path.is_file():
            raise ValueError(f"missing personal input: {path}")
    runtime = args.runtime.resolve()
    porpoise = args.porpoise.resolve()
    sdk = output / "libporpoise_constructors.c"
    preparer = ROOT / "scripts/dependencies/prepare_libporpoise_math.py"
    subprocess.run([sys.executable, str(preparer), "--source", str(porpoise), "--output", str(sdk)], check=True)
    baseline, generated_header = make_baselines(args, output)
    core = sorted((runtime / "src/core").glob("cpu*.c"))
    if len(core) != 6:
        raise ValueError("expected the six pinned runtime CPU translation units")
    abi = runtime.parent / "Source/Core/Core/PowerPC/StaticRecomp"
    executable = output / "porpoise_math_test.exe"
    common = [args.compiler] + args.compiler_arg + ["-std=c11", "-O2", "-ffp-contract=off", "-Wno-dll-attribute-on-redeclaration",
              "-DBLUEWAKE_LIBPORPOISE=1", '-DDOLRECOMP_CPU_HEADER="core/cpu.h"',
              f"-I{ROOT / 'cmake/composite'}", f"-I{runtime / 'include'}", f"-I{abi}"]
    sdk_object = output / "libporpoise_constructors.obj"
    sdk_command = [args.compiler] + args.compiler_arg + ["-std=c11", "-O2", "-ffp-contract=off", "-DLIBPORPOISE_PORT=1",
                   "-DC_MTXIdentity=bluewake_porpoise_mtx_identity",
                   "-DC_MTXTrans=bluewake_porpoise_mtx_trans", "-DC_MTXScale=bluewake_porpoise_mtx_scale",
                   f"-I{porpoise / 'include'}", "-c", str(sdk), "-o", str(sdk_object)]
    subprocess.run(sdk_command, check=True)
    units = [ROOT / "tests/porpoise_math_test.c", ROOT / "cmake/composite/native_math.c",
             ROOT / "cmake/composite/native_work_pool.c", ROOT / "cmake/composite/gather_pipe.c", baseline] + core
    command = common + list(map(str, units)) + [str(sdk_object), "-o", str(executable)]
    subprocess.run(command, check=True)
    completed = subprocess.run([str(executable), str(args.module.resolve()), str(args.cases), str(args.bench_calls)],
                               text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    print(completed.stdout, end="")
    if completed.returncode:
        raise RuntimeError(f"constructor qualification failed with exit {completed.returncode}")
    comparisons = re.findall(r"^([0-9A-F]{8}): (\d+) cases, (\d+) identical against oracle/raw/prepared, (\d+) declined unchanged, 0 mismatches$",
                             completed.stdout, re.M)
    if len(comparisons) != 3 or any(int(cases) != args.cases or int(accepted) + int(declined) != args.cases
                                   for _, cases, accepted, declined in comparisons):
        raise RuntimeError("incomplete constructor comparison report")
    benchmarks = {}
    for entry, round_id, raw, prepared, guarded, calls in re.findall(
            r"^BENCH ([0-9A-F]{8}) round=(\d+) raw=([\d.]+) prepared=([\d.]+) guarded=([\d.]+) ns/call calls=(\d+)$",
            completed.stdout, re.M):
        benchmarks.setdefault(entry, []).append({"round": int(round_id), "raw_ns": float(raw),
                                                 "prepared_ns": float(prepared), "guarded_ns": float(guarded),
                                                 "calls": int(calls)})
    if args.bench_calls and (len(benchmarks) != 3 or any(len(rounds) != 5 for rounds in benchmarks.values())):
        raise RuntimeError("incomplete interleaved benchmark report")
    for entry, rounds in benchmarks.items():
        medians = {kind: statistics.median(round[kind] for round in rounds)
                   for kind in ("raw_ns", "prepared_ns", "guarded_ns")}
        print(f"{entry}: matched prepared/guarded median ratio {medians['prepared_ns'] / medians['guarded_ns']:.3f}x")
    sources = set(units + [generated_header, sdk, preparer, Path(__file__).resolve(),
                          ROOT / "scripts/generate_composite.py", ROOT / "scripts/windows/fast_blocks.py",
                          ROOT / "scripts/windows/chunk_headers.py", ROOT / "cmake/composite/inline_fp.h",
                          ROOT / "cmake/composite/gather_pipe.h", ROOT / "cmake/composite/gather_pipe_batch.h",
                          ROOT / "cmake/composite/native_math.h", ROOT / "cmake/composite/porpoise_mtx.h",
                          ROOT / "cmake/composite/module_cpu_contract.h", abi / "StaticRecompABI.h"])
    sources.update((runtime / "include/core").glob("*.h"))
    sources.update((runtime / "src/core").glob("cpu*.h"))
    sources.update(porpoise / relative for relative in load("porpoise_preparer", str(preparer.relative_to(ROOT))).SOURCE_HASHES)
    label = lambda path: str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path)
    report = {
        "module": str(args.module.resolve()), "module_sha256": sha(args.module),
        "translation_sha256": sha(args.translation), "private_header_sha256": sha(args.header),
        "constructor_body_sha256": {f"{start:08X}": digest for start, _, digest in LEAVES},
        "runtime_revision": subprocess.check_output(["git", "-C", str(runtime.parent), "rev-parse", "HEAD"], text=True).strip(),
        "porpoise_revision": subprocess.check_output(["git", "-C", str(porpoise), "rev-parse", "HEAD"], text=True).strip(),
        "compiler": subprocess.check_output([args.compiler, "--version"], text=True).splitlines()[0],
        "compile_commands": [sdk_command, command],
        "source_sha256": {label(path): sha(path) for path in sorted(sources)},
        "comparisons": {entry: {"cases": int(cases), "accepted": int(accepted), "declined_unchanged": int(declined)}
                        for entry, cases, accepted, declined in comparisons},
        "benchmark_rounds": benchmarks,
        "benchmark_medians": {entry: {kind: statistics.median(round[kind] for round in rounds)
                                     for kind in ("raw_ns", "prepared_ns", "guarded_ns")}
                              for entry, rounds in benchmarks.items()},
        "output": completed.stdout,
        "scope": "Complete-state constructor equivalence with original personal module and matched raw/prepared O2 leaves. Constructor-call microbenchmark with a synthetic readiness callback; no routed module or gameplay/FPS qualification.",
    }
    report_path = args.report or output / "report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Oracle receipt: {report_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--module", type=Path, required=True)
    parser.add_argument("--translation", type=Path, required=True,
                        help="personal raw chunk_0194_text1_803096E0.c, before prepared-block rewrites")
    parser.add_argument("--header", type=Path, required=True, help="personal raw DOL generated.h")
    parser.add_argument("--porpoise", type=Path, default=ROOT.parent / "libPorpoise")
    parser.add_argument("--runtime", type=Path, default=ROOT / "ref/recompcore/GXRuntime")
    parser.add_argument("--compiler", default="clang")
    parser.add_argument("--compiler-arg", action="append", default=[],
                        help="extra compiler argument, e.g. --compiler-arg=--target=x86_64-pc-windows-msvc")
    parser.add_argument("--cases", type=int, default=60000)
    parser.add_argument("--bench-calls", type=int, default=1000000)
    parser.add_argument("--output", type=Path, default=ROOT / "build/porpoise-math-oracle")
    parser.add_argument("--report", type=Path)
    arguments = parser.parse_args()
    if arguments.cases < 1 or arguments.bench_calls < 0:
        parser.error("--cases must be positive and --bench-calls nonnegative")
    run(arguments)
