# Experimental module ThinLTO, adapted from Douglas Whittingham's work at
# DolRecomp 1ef0fcd60a491ba9b191dcaf94fd9419009c93c1. Prepared C stays the backend.
include_guard(GLOBAL)
option(BLUEWAKE_MODULE_THINLTO "Use experimental ThinLTO for the Windows C game module" OFF)

function(bluewake_enable_module_thinlto target)
  if(NOT BLUEWAKE_MODULE_THINLTO)
    return()
  endif()
  if(NOT WIN32 OR NOT CMAKE_C_COMPILER_ID STREQUAL "Clang")
    message(FATAL_ERROR "Module ThinLTO requires Windows Clang and lld-link")
  endif()
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "Module ThinLTO target does not exist: ${target}")
  endif()
  get_target_property(kind "${target}" TYPE)
  if(NOT kind STREQUAL "SHARED_LIBRARY")
    message(FATAL_ERROR "Module ThinLTO requires a shared game-module target")
  endif()
  if(ARGN)
    message(FATAL_ERROR "Module ThinLTO requires the prepared C backend, without external native objects")
  endif()
  get_target_property(applied "${target}" BLUEWAKE_MODULE_THINLTO_APPLIED)
  if(applied)
    return()
  endif()
  target_compile_options("${target}" PRIVATE -flto=thin)
  target_link_options("${target}" PRIVATE -flto=thin -fuse-ld=lld "LINKER:/OPT:LLDLTOJOBS=1")
  set_property(TARGET "${target}" PROPERTY BLUEWAKE_MODULE_THINLTO_APPLIED TRUE)
endfunction()
