# Source-only regression library for the source-audited GZLE01 health rules.
if(NOT TARGET bluewake_health_rules_prototype)
  set(_bw_health_root "${CMAKE_CURRENT_LIST_DIR}/..")
  add_library(bluewake_health_rules_prototype STATIC "${_bw_health_root}/runtime/host/src/health_rules.c")
  target_include_directories(bluewake_health_rules_prototype PUBLIC "${_bw_health_root}/runtime/host/src" "${_bw_health_root}/ref/recompcore/GXRuntime/include")
  target_compile_features(bluewake_health_rules_prototype PUBLIC c_std_11)
  if(BUILD_TESTING)
    add_executable(bluewake_health_rules_test "${_bw_health_root}/tests/health_rules_test.c")
    target_link_libraries(bluewake_health_rules_test PRIVATE bluewake_health_rules_prototype)
    if(TARGET gxruntime)
      target_link_libraries(bluewake_health_rules_test PRIVATE gxruntime)
    else()
      # Actual donor memory/journal helpers, no CPU/video/device initialization.
      target_sources(bluewake_health_rules_test PRIVATE
        "${_bw_health_root}/ref/recompcore/GXRuntime/src/guest_memory.c"
        "${_bw_health_root}/ref/recompcore/GXRuntime/src/guest_memory_dirty.c"
        "${_bw_health_root}/ref/recompcore/GXRuntime/src/core/cpu.c"
        "${_bw_health_root}/ref/recompcore/GXRuntime/src/core/cpu_exception.c")
      if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(bluewake_health_rules_test PRIVATE -ffunction-sections -fdata-sections)
        if(WIN32)
          target_link_options(bluewake_health_rules_test PRIVATE -Wl,/OPT:REF)
        else()
          target_link_options(bluewake_health_rules_test PRIVATE -Wl,--gc-sections)
        endif()
      endif()
    endif()
    if(UNIX)
      target_link_libraries(bluewake_health_rules_test PRIVATE m)
    endif()
    add_test(NAME bluewake_health_rules_test COMMAND bluewake_health_rules_test)
    set_tests_properties(bluewake_health_rules_test PROPERTIES TIMEOUT 25)
  endif()
endif()

# The fixture extracts actual slow/prepaid-fast caller bodies only when the
# private prepared tree exists. Unknown or changed shapes fail configuration.
function(_bw_health_extract file instruction op return_pc output)
  file(READ "${file}" _body)
  set(_needle "    // ${instruction}: ${op}")
  string(FIND "${_body}" "${_needle}" _begin)
  if(_begin LESS 0)
    message(FATAL_ERROR "Health fixture cannot locate native caller ${instruction}")
  endif()
  string(SUBSTRING "${_body}" ${_begin} -1 _tail)
  string(FIND "${_tail}" "\nbwend_" _end)
  if(_end LESS 0)
    message(FATAL_ERROR "Health fixture lacks slow caller end ${instruction}")
  endif()
  string(SUBSTRING "${_tail}" 0 ${_end} _slow)
  math(EXPR _after "${_begin}+${_end}")
  string(SUBSTRING "${_body}" ${_after} -1 _tail)
  string(FIND "${_tail}" "${_needle}" _begin)
  if(_begin LESS 0)
    message(FATAL_ERROR "Health fixture lacks prepaid-fast caller ${instruction}")
  endif()
  string(SUBSTRING "${_tail}" ${_begin} -1 _tail)
  string(FIND "${_tail}" "\n    goto bwend_" _end)
  if(_end LESS 0)
    message(FATAL_ERROR "Health fixture lacks fast caller end ${instruction}")
  endif()
  string(SUBSTRING "${_tail}" 0 ${_end} _fast)
  string(FIND "${_slow}" "bw_direct_call_ready(ctx, 0x${return_pc}u)" _guard)
  if(NOT _slow STREQUAL _fast OR _guard LESS 0)
    message(FATAL_ERROR "Health slow/fast shape or return guard differs at ${instruction}")
  endif()
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${output}.inc" "${_slow}")
endfunction()
if(TARGET bluewake_health_rules_test)
  if(DEFINED BLUEWAKE_HEALTH_PREPARED_SOURCE)
    set(_tree "${BLUEWAKE_HEALTH_PREPARED_SOURCE}/chunks_dol")
  else()
    set(_tree "${_bw_health_root}/build/mods-integration/composite-src/chunks_dol")
  endif()
  set(_fall "${_tree}/chunk_0069_text1_801156E0.c")
  set(_collision "${_tree}/chunk_0072_text1_801216E0.c")
  set(_heart "${_tree}/chunk_0048_text1_800C16E0.c")
  if(EXISTS "${_fall}" AND EXISTS "${_collision}" AND EXISTS "${_heart}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_fall}" "${_collision}" "${_heart}")
    _bw_health_extract("${_fall}" 801165F0 "bl      " 801165F4 health_fall_call_under_test)
    _bw_health_extract("${_collision}" 80121F54 "bl      " 80121F58 health_collision_call_under_test)
    _bw_health_extract("${_heart}" 800C2E1C "bctrl" 800C2E20 health_heart_call_under_test)
    _bw_health_extract("${_tree}/chunk_0069_text1_801156E0.c" 801165F0 "bl      " 801165F4 health_damage_call_0)
    _bw_health_extract("${_tree}/chunk_0069_text1_801156E0.c" 80116640 "bl      " 80116644 health_damage_call_1)
    _bw_health_extract("${_tree}/chunk_0069_text1_801156E0.c" 80117980 "bl      " 80117984 health_damage_call_2)
    _bw_health_extract("${_tree}/chunk_0069_text1_801156E0.c" 80118BA8 "bl      " 80118BAC health_damage_call_3)
    _bw_health_extract("${_tree}/chunk_0079_text1_8013D6E0.c" 8013F740 "bl      " 8013F744 health_damage_call_4)
    _bw_health_extract("${_tree}/chunk_0079_text1_8013D6E0.c" 8013F760 "bl      " 8013F764 health_damage_call_5)
    _bw_health_extract("${_tree}/chunk_0085_text1_801556E0.c" 80159678 "bl      " 8015967C health_damage_call_6)
    _bw_health_extract("${_tree}/chunk_0085_text1_801556E0.c" 8015969C "bl      " 801596A0 health_damage_call_7)
    target_compile_definitions(bluewake_health_rules_test PRIVATE BLUEWAKE_HEALTH_OPTIMIZED_CALL_FIXTURE=1 BLUEWAKE_DIRECT_CALLS=1)
    target_include_directories(bluewake_health_rules_test PRIVATE "${_bw_health_root}/cmake/composite" "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
endif()
