add_executable(bluewake_dialogue_speed_test
    "${BLUEWAKE_REPO_ROOT}/tests/dialogue_speed_test.c"
    "${BLUEWAKE_HOST_SRC}/dialogue_speed.c"
    "${BLUEWAKE_HOST_SRC}/game_events.c")
target_include_directories(bluewake_dialogue_speed_test PRIVATE "${BLUEWAKE_HOST_SRC}")
# An own-disc prepared tree supplies the actual optimized bctrl block. The
# shared production dispatcher/direct-call headers are always exercised when
# this additional reachability fixture is available; no game assets are used.
set(_dialogue_caller "${BLUEWAKE_REPO_ROOT}/build/mods-integration/composite-src/chunks_dol/chunk_0167_text1_8029D6E0.c")
if(EXISTS "${_dialogue_caller}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_dialogue_caller}")
    file(READ "${_dialogue_caller}" _dialogue_chunk)
    string(FIND "${_dialogue_chunk}" "    // 8029F35C: bctrl\n" _dialogue_begin)
    if(_dialogue_begin LESS 0)
        message(FATAL_ERROR "Dialogue fixture could not locate the audited character call")
    endif()
    string(SUBSTRING "${_dialogue_chunk}" ${_dialogue_begin} -1 _dialogue_tail)
    string(FIND "${_dialogue_tail}" "\nbwend_" _dialogue_end)
    if(_dialogue_end LESS 0)
        message(FATAL_ERROR "Dialogue fixture could not locate the optimized block end")
    endif()
    string(SUBSTRING "${_dialogue_tail}" 0 ${_dialogue_end} _dialogue_call)
    string(FIND "${_dialogue_call}" "bw_direct_call_ready(ctx, 0x8029F360u)" _dialogue_guard)
    if(_dialogue_guard LESS 0)
        message(FATAL_ERROR "Dialogue fixture requires the qualified dynamic return guard")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/dialogue_optimized_call_under_test.inc" "${_dialogue_call}")
    target_compile_definitions(bluewake_dialogue_speed_test PRIVATE
        BLUEWAKE_DIALOGUE_OPTIMIZED_CALL_FIXTURE=1 BLUEWAKE_DIRECT_CALLS=1)
    target_include_directories(bluewake_dialogue_speed_test PRIVATE
        "${BLUEWAKE_REPO_ROOT}/cmake/composite" "${CMAKE_CURRENT_BINARY_DIR}")
endif()

# MSG uses direct calls between chunks. Extract the real slow and prepaid-fast
# call bodies and require their return handshakes to agree. The fixture uses
# these bodies, the production direct-call/edge loop, and synthetic font/parser
# results; it does not need assets or the full translated module.
function(_bluewake_dialogue_extract_legacy_call chunk instruction return_pc output_name)
    file(READ "${chunk}" _chunk)
    set(_needle "    // ${instruction}: bl      ")
    string(FIND "${_chunk}" "${_needle}" _begin)
    if(_begin LESS 0)
        message(FATAL_ERROR "Dialogue fixture cannot locate legacy call ${instruction}")
    endif()
    string(SUBSTRING "${_chunk}" ${_begin} -1 _tail)
    string(FIND "${_tail}" "\nbwend_" _end)
    if(_end LESS 0)
        message(FATAL_ERROR "Dialogue fixture cannot locate legacy slow-call end")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_end} _slow)
    math(EXPR _after "${_begin} + ${_end}")
    string(SUBSTRING "${_chunk}" ${_after} -1 _tail)
    string(FIND "${_tail}" "${_needle}" _fast_begin)
    if(_fast_begin LESS 0)
        message(FATAL_ERROR "Dialogue fixture requires the legacy prepaid-fast call")
    endif()
    string(SUBSTRING "${_tail}" ${_fast_begin} -1 _tail)
    string(FIND "${_tail}" "\n    goto bwend_" _fast_end)
    if(_fast_end LESS 0)
        message(FATAL_ERROR "Dialogue fixture cannot locate legacy fast-call end")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_fast_end} _fast)
    if(NOT _slow STREQUAL _fast)
        message(FATAL_ERROR "Legacy slow/fast direct-call bodies differ at ${instruction}")
    endif()
    string(FIND "${_slow}" "bw_direct_call_ready(ctx, 0x${return_pc}u)" _guard)
    if(_guard LESS 0)
        message(FATAL_ERROR "Legacy call requires dynamic return handshake ${return_pc}")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${output_name}.inc" "${_slow}")
endfunction()
set(_legacy_message_caller "${BLUEWAKE_REPO_ROOT}/build/mods-integration/composite-src/chunks_dol/chunk_0132_text1_802116E0.c")
set(_legacy_parser_caller "${BLUEWAKE_REPO_ROOT}/build/mods-integration/composite-src/chunks_dol/chunk_0012_text1_800316E0.c")
if(EXISTS "${_dialogue_caller}" AND EXISTS "${_legacy_message_caller}" AND EXISTS "${_legacy_parser_caller}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${_legacy_message_caller}" "${_legacy_parser_caller}")
    _bluewake_dialogue_extract_legacy_call("${_legacy_message_caller}" 80214298 8021429C dialogue_legacy_call_under_test)
    _bluewake_dialogue_extract_legacy_call("${_legacy_parser_caller}" 800346B0 800346B4 dialogue_legacy_first_under_test)
    _bluewake_dialogue_extract_legacy_call("${_legacy_parser_caller}" 800346CC 800346D0 dialogue_legacy_next_under_test)
    target_compile_definitions(bluewake_dialogue_speed_test PRIVATE
        BLUEWAKE_DIALOGUE_LEGACY_OPTIMIZED_CALL_FIXTURE=1)
endif()
target_compile_features(bluewake_dialogue_speed_test PRIVATE c_std_11)
target_link_libraries(bluewake_dialogue_speed_test PRIVATE gxruntime)
find_package(Threads REQUIRED)
target_link_libraries(bluewake_dialogue_speed_test PRIVATE Threads::Threads)
if(UNIX)
    target_link_libraries(bluewake_dialogue_speed_test PRIVATE m)
endif()
add_test(NAME bluewake_dialogue_speed_test COMMAND bluewake_dialogue_speed_test)
set_tests_properties(bluewake_dialogue_speed_test PROPERTIES TIMEOUT 15)
