add_executable(bluewake_enhancement_hooks_test
    "${BLUEWAKE_REPO_ROOT}/tests/enhancement_hooks_test.c"
    "${BLUEWAKE_HOST_SRC}/enhancement_hooks.c"
    "${BLUEWAKE_HOST_SRC}/game_events.c")
target_include_directories(bluewake_enhancement_hooks_test PRIVATE "${BLUEWAKE_HOST_SRC}")
target_compile_features(bluewake_enhancement_hooks_test PRIVATE c_std_11)
target_link_libraries(bluewake_enhancement_hooks_test PRIVATE gxruntime)
if(UNIX)
    target_link_libraries(bluewake_enhancement_hooks_test PRIVATE m)
endif()

# Qualify real prepared optimized call bodies without building the full module
# or using assets. Both slow and prepaid-fast bodies must match, and the entry
# AND return must consult the dynamic host predicate. Unknown generated shapes
# fail configure instead of silently claiming dispatch reachability.
function(_bluewake_enhancement_extract chunk instruction return_pc output)
    file(READ "${chunk}" _chunk)
    set(_needle "    // ${instruction}: bl      ")
    string(FIND "${_chunk}" "${_needle}" _begin)
    if(_begin LESS 0)
        message(FATAL_ERROR "Enhancement fixture cannot locate ${instruction}")
    endif()
    string(SUBSTRING "${_chunk}" ${_begin} -1 _tail)
    string(FIND "${_tail}" "\nbwend_" _end)
    if(_end LESS 0)
        message(FATAL_ERROR "Enhancement fixture cannot locate slow-call block end")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_end} _slow)
    math(EXPR _after "${_begin} + ${_end}")
    string(SUBSTRING "${_chunk}" ${_after} -1 _tail)
    string(FIND "${_tail}" "${_needle}" _begin)
    if(_begin LESS 0)
        message(FATAL_ERROR "Enhancement fixture requires prepaid-fast caller")
    endif()
    string(SUBSTRING "${_tail}" ${_begin} -1 _tail)
    string(FIND "${_tail}" "\n    goto bwend_" _end)
    if(_end LESS 0)
        message(FATAL_ERROR "Enhancement fixture cannot locate fast-call block end")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_end} _fast)
    if(NOT _slow STREQUAL _fast)
        message(FATAL_ERROR "Enhancement slow/fast call bodies differ at ${instruction}")
    endif()
    string(FIND "${_slow}" "bw_direct_call_ready(ctx, 0x${return_pc}u)" _guard)
    if(_guard LESS 0)
        message(FATAL_ERROR "Enhancement caller lacks dynamic return handshake ${return_pc}")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${output}.inc" "${_slow}")
endfunction()
set(_enhancement_tree "${BLUEWAKE_REPO_ROOT}/build/mods-integration/composite-src")
set(_enhancement_wind "${_enhancement_tree}/chunks_d_a_wbird_118/chunk_0000_rel1_C1F100DC.c")
set(_enhancement_boots "${_enhancement_tree}/chunks_dol/chunk_0070_text1_801196E0.c")
if(EXISTS "${_enhancement_wind}" AND EXISTS "${_enhancement_boots}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_enhancement_wind}" "${_enhancement_boots}")
    _bluewake_enhancement_extract("${_enhancement_wind}" C1F10620 C1F10624 enhancement_wind_call_under_test)
    _bluewake_enhancement_extract("${_enhancement_boots}" 801198B8 801198BC enhancement_boots_call_under_test)
    target_compile_definitions(bluewake_enhancement_hooks_test PRIVATE BLUEWAKE_ENHANCEMENT_OPTIMIZED_CALL_FIXTURE=1 BLUEWAKE_DIRECT_CALLS=1)
    target_include_directories(bluewake_enhancement_hooks_test PRIVATE "${BLUEWAKE_REPO_ROOT}/cmake/composite" "${CMAKE_CURRENT_BINARY_DIR}")
endif()
add_test(NAME bluewake_enhancement_hooks_test COMMAND bluewake_enhancement_hooks_test)
set_tests_properties(bluewake_enhancement_hooks_test PROPERTIES TIMEOUT 20)
