# Source-only health fixtures. No game/native UI/device/video initialization.
if(BUILD_TESTING AND NOT TARGET bluewake_health_host_test)
  include("${CMAKE_CURRENT_LIST_DIR}/BlueWakeHealthRulesPrototype.cmake")
  get_filename_component(_health_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  file(READ "${_health_root}/runtime/host/src/health_host.c" _health_adapter)
  string(REPLACE [[#include "health_module_contract.h"]] [[#include "health_synthetic_contract.h"]] _health_synthetic "${_health_adapter}")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/health_host_synthetic.c" "${_health_synthetic}")
  add_executable(bluewake_health_host_test "${_health_root}/tests/health_host_test.c" "${CMAKE_CURRENT_BINARY_DIR}/health_host_synthetic.c")
  add_executable(bluewake_health_configuration_thread_test "${_health_root}/tests/health_configuration_thread_test.cpp" "${_health_root}/runtime/host/src/health_host.c")
  foreach(t IN ITEMS bluewake_health_host_test bluewake_health_configuration_thread_test)
    target_include_directories(${t} PRIVATE "${_health_root}/tests" "${_health_root}/runtime/host/src"
      "${_health_root}/ref/recompcore/GXRuntime/include" "${_health_root}/ref/recompcore/Source/Core/Core/PowerPC/StaticRecomp")
    target_link_libraries(${t} PRIVATE bluewake_health_rules_prototype)
    target_compile_features(${t} PRIVATE c_std_11)
    if(TARGET gxruntime)
      target_link_libraries(${t} PRIVATE gxruntime)
      set_target_properties(${t} PROPERTIES LINKER_LANGUAGE CXX)
    else()
      target_sources(${t} PRIVATE "${_health_root}/ref/recompcore/GXRuntime/src/guest_memory.c" "${_health_root}/ref/recompcore/GXRuntime/src/guest_memory_dirty.c"
        "${_health_root}/ref/recompcore/GXRuntime/src/core/cpu.c" "${_health_root}/ref/recompcore/GXRuntime/src/core/cpu_exception.c")
      target_compile_options(${t} PRIVATE -ffunction-sections -fdata-sections)
      if(WIN32)
        target_link_options(${t} PRIVATE -Wl,/OPT:REF)
      else()
        target_link_options(${t} PRIVATE -Wl,--gc-sections)
        target_link_libraries(${t} PRIVATE m)
      endif()
    endif()
    add_test(NAME ${t} COMMAND ${t})
    set_tests_properties(${t} PROPERTIES TIMEOUT 30)
  endforeach()
  target_compile_features(bluewake_health_configuration_thread_test PRIVATE cxx_std_17)
  find_package(Threads REQUIRED)
  target_link_libraries(bluewake_health_configuration_thread_test PRIVATE Threads::Threads)
  target_compile_options(bluewake_health_configuration_thread_test PRIVATE -UNDEBUG)
  get_target_property(_health_core_defs bluewake_health_rules_test COMPILE_DEFINITIONS)
  if("BLUEWAKE_HEALTH_OPTIMIZED_CALL_FIXTURE=1" IN_LIST _health_core_defs)
    # Actual public main predicate is extracted without game bytes. Unrelated
    # policies are fixture stand-ins; supplied-CPU health observation is real.
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    execute_process(COMMAND "${Python3_EXECUTABLE}" -B -S
      "${_health_root}/tests/observation_facts/prepare.py" --repo "${_health_root}"
      --legacy-observation-output "${CMAKE_CURRENT_BINARY_DIR}/health_main_skip_under_test.inc"
      RESULT_VARIABLE _health_skip_prepare_result ERROR_VARIABLE _health_skip_prepare_error)
    if(NOT _health_skip_prepare_result EQUAL 0)
      message(FATAL_ERROR "Health main facts0 skip seam: ${_health_skip_prepare_error}")
    endif()
    file(READ "${CMAKE_CURRENT_BINARY_DIR}/health_main_skip_under_test.inc" _health_skip)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
      "${_health_root}/runtime/host/src/main.c"
      "${_health_root}/tests/observation_facts/prepare.py"
      "${_health_root}/tests/observation_facts/reference.inc")
    string(FIND "${_health_skip}" "!bw_health_host_observes(cpu,address)" _health_guard)
    if(_health_guard LESS 0)
      message(FATAL_ERROR "Health main supplied-CPU skip seam is missing")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/health_main_skip_under_test.inc" "${_health_skip}")
    target_compile_definitions(bluewake_health_host_test PRIVATE BLUEWAKE_HEALTH_OPTIMIZED_CALL_FIXTURE=1 BLUEWAKE_DIRECT_CALLS=1 BW_HEALTH_TEST_HOST=1 BLUEWAKE_HEALTH_MAIN_SKIP_FIXTURE=1)
    target_include_directories(bluewake_health_host_test PRIVATE "${_health_root}/cmake/composite" "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
endif()
