# Exact production host-edge functions, with synthetic SDL device levels only.
# No SDL runtime, native input, windows, renderer or game assets.
set(_jump_source "${BLUEWAKE_HOST_SRC}/jump_button.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_jump_source}")
file(READ "${_jump_source}" _jump_text)
function(_bluewake_extract_jump output begin_marker end_marker)
    string(FIND "${_jump_text}" "${begin_marker}" _begin)
    if(end_marker STREQUAL "EOF")
        string(LENGTH "${_jump_text}" _end)
    else()
        string(FIND "${_jump_text}" "${end_marker}" _end)
    endif()
    if(_begin LESS 0 OR _end LESS _begin)
        message(FATAL_ERROR "Could not locate ${begin_marker} for jump input regression")
    endif()
    math(EXPR _length "${_end}-${_begin}")
    string(SUBSTRING "${_jump_text}" ${_begin} ${_length} _function)
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${output}" "${_function}")
endfunction()
_bluewake_extract_jump(jump_touch_under_test.inc "void bluewake_jump_button_touch(" "static unsigned g_presses_seen;")
_bluewake_extract_jump(jump_event_under_test.inc "void bluewake_jump_button_event(" "void bluewake_jump_button_reload(")
_bluewake_extract_jump(jump_discard_under_test.inc "static bool bumper_pressed(" "void bluewake_jump_button_retrace(")
_bluewake_extract_jump(jump_retrace_under_test.inc "void bluewake_jump_button_retrace(" "EOF")
add_executable(bluewake_jump_input_test "${BLUEWAKE_REPO_ROOT}/tests/jump_input_test.c")
target_compile_features(bluewake_jump_input_test PRIVATE c_std_11)
target_compile_definitions(bluewake_jump_input_test PRIVATE SDL_STATIC)
target_include_directories(bluewake_jump_input_test PRIVATE "${CMAKE_CURRENT_BINARY_DIR}"
    "${GXRUNTIME_DIR}/include" $<TARGET_PROPERTY:${AURORA_SDL3_TARGET},INTERFACE_INCLUDE_DIRECTORIES>)
target_link_libraries(bluewake_jump_input_test PRIVATE gxruntime)
set_target_properties(bluewake_jump_input_test PROPERTIES LINKER_LANGUAGE CXX)
add_test(NAME bluewake_jump_input_test COMMAND bluewake_jump_input_test)
set_tests_properties(bluewake_jump_input_test PROPERTIES LABELS controls TIMEOUT 15)
