# Synthetic copied facts plus actual store receipts; no game, guest or devices.
include_guard(GLOBAL)
get_filename_component(_bw_transaction_test_repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/BlueWakeRandomizerSeed.cmake")
if(NOT TARGET bluewake_randomizer_transaction_test)
  add_executable(bluewake_randomizer_transaction_test "${_bw_transaction_test_repo}/tests/randomizer_transaction_test.cpp")
  target_link_libraries(bluewake_randomizer_transaction_test PRIVATE bluewake_randomizer_seed)
  set_target_properties(bluewake_randomizer_transaction_test PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED YES)
  if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    target_compile_options(bluewake_randomizer_transaction_test PRIVATE /UNDEBUG)
  else()
    target_compile_options(bluewake_randomizer_transaction_test PRIVATE -UNDEBUG)
  endif()
  add_test(NAME bluewake_randomizer_transaction_test COMMAND bluewake_randomizer_transaction_test "${CMAKE_CURRENT_BINARY_DIR}/randomizer-transactions")
  set_tests_properties(bluewake_randomizer_transaction_test PROPERTIES TIMEOUT 60 LABELS "source-only;randomizer;synthetic-observation")
endif()
